### PR TITLE
Added compatibility for Polymer 2.x

### PR DESCRIPTION
**Pull request by jawadsh123**
I've tested the changes on Polymer 1.7+ and they seem to be working.
I was not able to test them on Polymer 1.5. :( 
Could you please review and see if this works with 1.5?

And regarding webcomponents.org, I haven't really hosted anything on their either.
Will see what can be done about that :)

### CODE REVIEW

**Comment by jawadsh123** [comment]
I was trying to convert this component's declaration from Polymer Base to the new ES6 class based sytax too, but @vguillou seems to have used a lot of methods provided by Polymer.Base and migrating all of those was becoming a bit of a pain.
So, I gave up on that front since I'm not really well versed with the older versions of Polymer.

If you ever have time for it, I think it will be worth it to convert to the class based syntax since it's now turning into a standard.

**Comment by jawadsh123** [comment]
This PR fixes #1

**Comment by OvermindDL1** [comment]
> I've tested the changes on Polymer 1.7+ and they seem to be working.
> I was not able to test them on Polymer 1.5. :(
> Could you please review and see if this works with 1.5?

Eh, I'm on 1.7 as well, and as it is mostly backwards compatible with 1.5 we can just make it the minimum then.  I'm good with that, since as far as I know we are the only two users.  :-)

> And regarding webcomponents.org, I haven't really hosted anything on their either.
> Will see what can be done about that :)

I'll see if I can look in to that soon too.

> I was trying to convert this component's declaration from Polymer Base to the new ES6 class based sytax too, but @vguillou seems to have used a lot of methods provided by Polymer.Base and migrating all of those was becoming a bit of a pain.
> So, I gave up on that front since I'm not really well versed with the older versions of Polymer.

Yeah I noticed that as well, I originally tried rewriting it but it was going to take too long so I gave up due to lack of time.  I prefer ES6 syntax whenever possible (I am highly pro-ES6-modules especially).

> If you ever have time for it, I think it will be worth it to convert to the class based syntax since it's now turning into a standard.

I entirely agree!  :-)

I cursory check looks like the code is perfect.  I'll go ahead and merge it and when I bring it in at the next system update here I'll do a more thorough test, but it looks perfect as is.  Thanks much!

I'll look in to webcomponents.org soon, maybe today if I get some time.  :-)

**Comment by OvermindDL1** [comment]
A new name would have to be given it seems.  For now I went ahead and just changed the readme to how to grab it from git instead.

**Pull request merged**
